language: python

install:
  - pip install -r requirements.txt

script: echo foo

deploy:
   edge: true
   provider: cloudfoundry
   username: jprakash.ora@gmail.com
   password: prakash
   api: https://api.run.pivotal.io
   organization: success.io
   space: development
