language: python

env:
 - PORT=5001
install:
  - pip install -r requirements.txt

# command to run tests
script: python tests.py

deploy:
   edge: true
   provider: cloudfoundry
   username: jprakash.ora@gmail.com
   password: prakash
   api: https://api.run.pivotal.io
   organization: success.io
   space: development
